### ISSUE TITLE
OpenDA hangs after an error occured

### ISSUE THREAD

**Issue by tyralla** [hydpy-dev/OpenDA#1] opened 2019-01-25 10:10 UTC
After some errors, OpenDA prints a message but does not finish the process afterwards. For example, when there is a typo in the "modelFactory" argument "configFile“.

I am not sure whether this problem relates to the HydPy wrapper or OpenDA in general.

**Comment by GernotBelger** [comment] 2021-02-26 19:03
I was unable to reproduce this issue, can you provider more detailed infomation? However this might have been indirectly fixed with the  0.8.0 tag.
Was it the hydpy process that kept running or the java openda process?

**Comment by tyralla** [comment] 2021-03-12 11:36
It's the Java-OpenDA process that keeps the process alive.  OpenDA prints the following error information if the adapter cannot start the HydPy-Server:

```
(venv) C:\HydPy\OpenDA\demos\openda_projects\DUD>oda_run_batch main.oda
OPENDADIR set to C:\openda_2.4.5\bin\
"System set to win32_ifort"
Application initializing
Application initializing
OpenDA version 2.4.5.-1 May 27 2020
seriesTrees[0]<?xml version="1.0"?>
<timeSeries id="dill_nodes_sim_series" status="use" standardDeviation="2.0">data/dill.discharge.noos</timeSeries>

status=use
Starting Algorithm:
        className: org.openda.algorithms.Dud
        dir.: C:\HydPy\OpenDA\demos\openda_projects\DUD
        config.: algorithm.xml
Dud initialisation (stoch. obs. and stoch. model have been set)
Retrieving initial parameters from model
HydPyServer 0 - 8080: starting ...
Working-Directory:
C:\HydPy\OpenDA\demos\hydpy_projects
Command-Line:
python.exe hy.py start_server 8080 LahnH C:\HydPy\OpenDA\demos\openda_projects\DUD\hydpy.xml
log4j:WARN No appenders could be found for logger (org.apache.http.client.protocol.RequestAddCookies).
log4j:WARN Please initialize the log4j system properly.
HydPyServer 0 - 8080: waiting for startup...
HydPyServer 0 - 8080: Failed to connect to HydPy-Server
org.hydpy.openda.server.HydPyServerException: HydPyServer 0 - 8080: unexpectedly terminated
        at org.hydpy.openda.server.HydPyServerStarter.tryCallServer(HydPyServerStarter.java:202)
        at org.hydpy.openda.server.HydPyServerStarter.doStart(HydPyServerStarter.java:112)
        at org.hydpy.openda.server.HydPyServerStarter$1.call(HydPyServerStarter.java:69)
        at org.hydpy.openda.server.HydPyServerStarter$1.call(HydPyServerStarter.java:65)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
org.hydpy.openda.server.HydPyServerException: HydPyServer 0 - 8080: unexpectedly terminated
        at org.hydpy.openda.server.HydPyServerStarter.tryCallServer(HydPyServerStarter.java:202)
        at org.hydpy.openda.server.HydPyServerStarter.doStart(HydPyServerStarter.java:112)
        at org.hydpy.openda.server.HydPyServerStarter$1.call(HydPyServerStarter.java:69)
        at org.hydpy.openda.server.HydPyServerStarter$1.call(HydPyServerStarter.java:65)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
HydPyServer 0 - 8080: shut down terminated
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: Failed to start HydPy Server
        at org.openda.application.ApplicationRunner.startApplication(ApplicationRunner.java:357)
        at org.openda.application.ApplicationRunner.startApplication(ApplicationRunner.java:342)
        at org.openda.application.ApplicationRunnerSingleThreaded.initialize(ApplicationRunnerSingleThreaded.java:38)
        at org.openda.application.OpenDaApplication.runApplicationBatch(OpenDaApplication.java:119)
        at org.openda.application.OpenDaApplication.main(OpenDaApplication.java:108)
Caused by: java.lang.RuntimeException: Failed to start HydPy Server
        at org.hydpy.openda.server.HydPyServerManager.getOrCreateServer(HydPyServerManager.java:165)
        at org.hydpy.openda.server.HydPyServerManager.createInstance(HydPyServerManager.java:135)
        at org.hydpy.openda.server.HydPyServerManager.getOrCreateInstance(HydPyServerManager.java:126)
        at org.hydpy.openda.HydPyModelFactory.createFactory(HydPyModelFactory.java:107)
        at org.hydpy.openda.HydPyModelFactory.getFactory(HydPyModelFactory.java:90)
        at org.hydpy.openda.HydPyModelFactory.getInstance(HydPyModelFactory.java:243)
        at org.openda.blackbox.wrapper.BBStochModelFactory.getInstance(BBStochModelFactory.java:146)
        at org.openda.algorithms.BaseDud.setStochComponents(BaseDud.java:123)
        at org.openda.application.ApplicationRunner.startApplication(ApplicationRunner.java:352)
        ... 4 more
Caused by: org.hydpy.openda.server.HydPyServerException: HydPyServer 0 - 8080: unexpectedly terminated
        at org.hydpy.openda.server.HydPyServerStarter.tryCallServer(HydPyServerStarter.java:202)
        at org.hydpy.openda.server.HydPyServerStarter.doStart(HydPyServerStarter.java:112)
        at org.hydpy.openda.server.HydPyServerStarter$1.call(HydPyServerStarter.java:69)
        at org.hydpy.openda.server.HydPyServerStarter$1.call(HydPyServerStarter.java:65)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Error running OpenDA - please check the error messages
Drücken Sie eine beliebige Taste . . .

```

**Comment by GernotBelger** [comment] 2021-03-12 12:25
"Drücken Sie eine beliebige Taste . . ." does it stil hang after you print any key?

**Comment by tyralla** [comment] 2021-03-12 13:32
No, it doesn't. But that's inconvenient when using OpenDA within a larger workflow. For examples, our integration tests do not report errors but hang infinitely.

**Comment by GernotBelger** [comment] 2021-03-12 16:04
Ah ok, yes this is a property of the oda_run_batch.bat of OpenDA and can't be changed by us. The batch will always pause if it encounters an error.
You could either directly start the java application or make a copy of the batch and modify it.

**Closed as completed** 2021-03-12 16:04 UTC
Labels: wontfix
